Set goals
Timo-Thees/Capstone pull request #18
Opened 2022-12-06 10:48 UTC by Timo-Thees

Created the page to set a daily word goal and reserve times for writing.

I want to focus on more core user storys of my project, otherwise I fear I will get bogged down in less important sideshows.
Therefore, the current state has some known issues I want to address at a later stage:

- Has currently no save functionallity
- not styled
- Delete function works, but only shows its effect if another timeslot is deleted

2022-12-06 11:12 UTC, actyvystom reviewed
Good work and a lean PR to review!
Though please check your `handleDeleteTimeslot` function and correct the state update.

2022-12-06 11:12 UTC, actyvystom commented on components/SetGoals.js
> +    writingTime.splice(deleteEntry, 1);
**Attention:**
Here you are manipulating a state variable directly via splice method... please use the corresponding state setter (`setWritingTime`) to change the state variable to avoid inconsistent state variables.

2022-12-07 11:04 UTC, stefankorder requested changes
Looks good so far!

2022-12-07 11:04 UTC, stefankorder commented on components/SetGoals.js
> +                })}{" "}
There is a unnecessary space you should delete.
```suggestion
                })}
```

2022-12-07 11:04 UTC, stefankorder commented on components/SetGoals.js
> +                  if (timeslot.weekday === day) {
If you only want to display one weekday, a find method would be the better solution.

2022-12-07 11:22 UTC, Timo-Thees commented on components/SetGoals.js
> +                  if (timeslot.weekday === day) {
No, I want to display all weekdays side by side

2022-12-07 11:27 UTC, Timo-Thees commented on components/SetGoals.js
> +                })}{" "}
Thanks! Removed

2022-12-07 11:27 UTC, Timo-Thees commented on components/SetGoals.js
> +  /* const [goals, setGoals] = useState({dailyGoal: 0, writingTimes: {}});*/
Thanks! Removed.

2022-12-07 14:03 UTC, merged