Save in local storage
Timo-Thees/Capstone pull request #25
Opened 2022-12-15 13:16 UTC by Timo-Thees

Included in this feature:
- Projects are now saved in local storage
- added the option to overwrite a project if both projects have the same name
- added option to delete projects
- popup to reduce risk of accidental deletions

2022-12-15 13:36 UTC, stefankorder requested changes
Good work! Take a look at my comments. Maybe there are a few other places you could implement my suggestions.

2022-12-15 13:36 UTC, stefankorder commented on components/Editor.js
> +      )}
You could write it also like this:

```suggestion
      {finalCount.closingMessage &&
      !nameTakenContent.taken && (
        <ClosingPopup
          finalCount={finalCount}
          setFinalCount={setFinalCount}
          handleChangePage={handleChangePage}
        />
      )}
```

2022-12-15 13:36 UTC, stefankorder commented on components/Projects.js
> +      )}
You could also write it like this:

```suggestion
      {deletePopup && (
        <DeleteConfirm
          setDeletePopup={setDeletePopup}
          idForDeletion={idForDeletion}
          myProjects={myProjects}
          setMyProjects={setMyProjects}
        />
      )}
```

2022-12-15 14:02 UTC, Timo-Thees commented on components/Projects.js
> +      )}
Implementing the code changes produces a prettier error

2022-12-15 14:22 UTC, Timo-Thees commented
Thank you for your review! I am aware that there must be a more elegant way to write the annotated lines in the code. However, implementing the requested changes resulted in a failure of the first test. Therefore I reverted back to the previous code

2022-12-16 11:15 UTC, stefankorder approved these changes
Good work! Just 2 hints.

2022-12-16 11:15 UTC, stefankorder commented on components/Editor.js
>      <div>
Maybe you could use a Fragment `<>` insgtead a `<div>` at this point.

2022-12-16 11:15 UTC, stefankorder commented on pages/index.js
>          <NameTaken
You could use a logical "and" `&&` instead a "ternary" `? :` in such cases where the falsy value is just a Fragment or an empty string.

2022-12-16 13:50 UTC, merged